# Generated by Django 4.0.6 on 2022-08-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SE', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'user'},
        ),
    ]
