# Generated by Django 4.0.6 on 2022-08-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
    ]
